### ISSUE TITLE
Example inputs for transaction{} object used in (*EthRPC).EthSendTransactionl()

### ISSUE THREAD

**Issue by NiklasKunkel** [onrik/ethrpc#2]
Trying to use the EthSendTransaction() function and having some trouble with the inputs used in the transaction{} object.

It would help alot if you could add an example to the README demonstrating the values used in the transaction{} object and what they represent.

**Comment by onrik** [comment]
Can you provide your code example please. Also you can read origin docs for ethereum api https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction
