### ISSUE TITLE
EthGetBlockByHash always return response

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [onrik/ethrpc#21]
Example:`eth_getBlockByHash` rpc call return null, if block was not found, which might happen when node is de-synchronised. In this case EthGetBlockByHash api method will return nil error, and empty response. Expected behaviour in this case would be return nil in response.

**Comment by onrik** [comment]
Do you mean should return nil response and nil error?

**Comment by AndrewSamokhvalov** [comment]
I believe it should be nil block response because schema of method `(*Block, error)`, so it was expected to have nil block, if daemon returned "null" on block request.

**Comment by AndrewSamokhvalov** [comment]
@onrik Do you plan to change behaviour, or should I do that in my fork?

**Comment by onrik** [comment]
Fixed.
