### ISSUE TITLE
getbalabce The value returned is not correct   

### ISSUE THREAD

**Issue by chaogo** [onrik/ethrpc#24]
The value returned is incorrect

but  response is  right

**Comment by onrik** [comment]
@chaogo can you provide example please?

**Comment by chaogo** [comment]
package walletethdb

import (
	"fmt"
	"github.com/onrik/ethrpc"
	"log"
	"testing"
)

func Test(t *testing.T) {

	client := ethrpc.New("https://ropsten.infura.io")

	_, err := client.Web3ClientVersion()
	if err != nil {
		log.Fatal("节点连接失败：",err)
	}
	int ,err := client.EthGetBalance("0xc548c20F02A7fd669c86C881A0c243fdbD51ACd5","latest")
	fmt.Print("bigint",int)
}


![_20181218101908](https://user-images.githubusercontent.com/39609358/50128006-65620b00-02ae-11e9-9677-cc65f48cb333.png)

but  actual value 
![1545099621 1](https://user-images.githubusercontent.com/39609358/50128056-9b06f400-02ae-11e9-9e70-b34aab2c8e09.jpg)

**Comment by onrik** [comment]
It works properly.
```go
client := ethrpc.New("https://ropsten.infura.io")

_, err := client.Web3ClientVersion()
if err != nil {
	log.Fatal(err)
}
balance, err := client.EthGetBalance("0xc548c20F02A7fd669c86C881A0c243fdbD51ACd5","latest")
fmt.Print(balance.String())
```

**Comment by chaogo** [comment]
> 它工作正常。
> 
> ```go
> client  ：= ethrpc。新的（“ https://ropsten.infura.io ”）
> 
> _，错误 ：=客户。Web3ClientVersion（）
>  if err！= nil {
> 	登录。致命（错）
> }
> 平衡，错误 ：=客户。EthGetBalance（“ 0xc548c20F02A7fd669c86C881A0c243fdbD51ACd5 ”，“最新”）
> FMT。打印（余额。字符串（））
> ```

Thank you very much  , Do you know  string to bigint?   I didn't find it.
