### ISSUE TITLE
Support IPC

### ISSUE THREAD

**Issue by atoulme** [onrik/ethrpc#26]
It looks ethrpc (nice project!) doesn't support a local UNIX socket connection. Would it be possible to add IPC support?

**Comment by onrik** [comment]
You can use custom http client over unix socket. Example https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74

**Comment by atoulme** [comment]
Sure, I was looking for a bit more convenience, as the current impl uses http.DefaultClient (https://github.com/onrik/ethrpc/blob/master/ethrpc.go#L50) and doesn't allow to inject our own.

I guess it's acceptable to create our own flavor of `New` method that customizes the HttpClient.

**Comment by onrik** [comment]
You can use option [WithHttpClient](https://github.com/onrik/ethrpc/blob/master/options.go#L17).
