### ISSUE TITLE
EthGetBlockByNumber has first parameter of type INT

### ISSUE THREAD

**Issue by Morzaka** [onrik/ethrpc#31]
The EthGetBlockByNumber method has the first parameter of type INT.
The first parameter takes a block number.
In the future, this type will create problems with large numbers of blocks that are constantly increasing.
My advice is to use UINT64 or implement your own bigInt type.

**Comment by onrik** [comment]
Now we have about 8 millions blocks after 4 years running. With this pace int will be overflow in 4.5e+12 years.

**Comment by Morzaka** [comment]
Ok
