### ISSUE TITLE
Can you give me EthCall example

### ISSUE THREAD

**Issue by y-zono** [onrik/ethrpc#6]
**Summary**

I love your tool. It is very convenient and easy to use. Can you give me an example of EthCall. I got error like the following. The below ethcall is for getting ERC20 token name with the contract address.

**Steps to Reproduce**

1. run EthCall()

* test.go

```
var client *ethrpc.EthRPC

func EthCall() string {
	result, err := client.EthCall(ethrpc.T{To: "0x41e5560054824ea6b0732e656e3ad64e20e94e45", Data: "0x06fdde03"}, "latest")
	if err != nil {
		panic(err)
	}
	return result
}
```

**Expected Results**

Return the result same as normal JSON RPC

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x41e5560054824ea6b0732e656e3ad64e20e94e45","data":"0x06fdde03"}, "latest"],"id":83}' http://localhost:xxxx

{"jsonrpc":"2.0","id":83,"result":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000054369766963000000000000000000000000000000000000000000000000000000"}
```

**Actual Results**

Error occurred.

```
panic: Error -32602 (invalid argument 0: hex string has length 0, want 40 for common.Address)
```

**Comment by onrik** [comment]
You can enable debug mode and check raw request data.

**Comment by onrik** [comment]
Look like you forgot fill "from" field.

**Comment by y-zono** [comment]
Thank you for your quick response. The problem was solved after I added "From". My issue was solved and I will use "debug" when I get error.

```
func EthCall() string {
	result, err := client.EthCall(ethrpc.T{From: "0x9f43eec1555cf191b15f1788b0c9ff4e43b7f215", To: "0x41e5560054824ea6b0732e656e3ad64e20e94e45", Data: "0x06fdde03"}, "latest")
	if err != nil {
		panic(err)
	}
	return result
}
```

**Comment by Vishwas1** [comment]
Guys getting this error while calling a getter method of smart contract ... "Error : invalid argument 0: hex string has length 0, want 40 for common.Address"
I have already checked that from has value in it.. "0x79c2d9e000dcf67cae1a94ff6e4a61be256f95a9"
and by the way getAllMediaIds() method does not need any parameter

![image](https://files.gitter.im/ethereum/web3.js/bKnB/image.png)

But this works perfectly fine with testrpc
